# Generated by Django 4.2.4 on 2023-09-12 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_messagemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='messagemodel',
            name='message_time',
        ),
    ]
